//// The SIMD conformance headline (P6-10 §A/§C) — drives the `simd_*.wast` file set (the largest
//// slice of the whole testsuite: `v128` + ~236 lane instructions) through the REAL pipeline and
//// asserts `fail == 0 && pass > 0`, with a per-FAMILY breakdown so a single mis-lowered lane family
//// (int / float / mem / lane) fails on a NAMED group, not diffusely.
////
//// This is the true integration proof of `rt_simd` (P6-07) / `emit_core` (P6-06) / `lower` (P6-05) /
//// `decode` (P6-03): every SIMD `assert_return` is a spec-baked expected `v128` (or a scalar for
//// extract-lane / `any_true` / `all_true` / `bitmask`), compared **bit-exact lane-wise** by the
//// oracle (integer lanes exact; f32/f64 lanes by bit-equality OR NaN class — M3); the SIMD-memory
//// traps route through the bounds-checked `rt_mem` seam and match the existing `"out of bounds
//// memory access"` phrase (no new `TrapReason`). Spec-cited (the vector-instruction set + the SIMD
//// NaN-propagation rules), differential (the baked `.wast` expected values), never a change-detector.
////
//// Coverage adapts to whatever `simd_*.json` are present in `fixtures/` (the vendor step converts
//// all 59 files; 58 flagless + `simd_memory-multi` under `--enable-multi-memory`). If NONE are
//// present (a fresh checkout with only the curated subset), the test no-ops with a note — the
//// vendored SIMD set is gitignored and regenerated by `vendor/vendor.sh`.

import gleam/int
import gleam/io
import gleam/list
import gleam/string
import scribbler/conformance/driver
import scribbler/conformance/ffi
import scribbler/conformance/fixture
import scribbler/conformance/runner.{type Report}

const fixtures_dir = "test/scribbler/conformance/fixtures"

/// The SIMD headline: over every present `simd_*.json`, `fail == 0` and `pass > 0`, with a
/// per-family (int / float / mem+lane / const+conv/misc) breakdown printed. A wrong lane, a
/// double-rounded `f32x4` op, a mis-endianned `v128.store`, or a missing SIMD-memory OOB trap turns
/// the owning family red. Runs under the Safe profile (Baseline optimizer); the tier + Unsafe proof
/// is `conformance_test`/`simd_differential_test`.
pub fn simd_suite_fail_zero_test() {
  let files = simd_files()
  case files {
    [] -> {
      io.println(
        "\n[simd] no simd_*.json fixtures present; run test/scribbler/conformance/vendor/vendor.sh",
      )
      Nil
    }
    _ -> {
      let d = driver.pipeline()
      io.println(
        "\n=== SIMD conformance (Tier-A, "
        <> int.to_string(list.length(files))
        <> " files) ===",
      )
      let #(total, fam) =
        list.fold(
          files,
          #(runner.empty_report(), new_families()),
          fn(acc, name) {
            let #(tot, fams) = acc
            let rep = run_one(d, name)
            #(runner.merge(tot, rep), add_family(fams, family_of(name), rep))
          },
        )
      print_families(fam)
      io.println(
        "  SIMD TOTAL  pass="
        <> int.to_string(total.pass)
        <> "  skip="
        <> int.to_string(total.skip)
        <> "  fail="
        <> int.to_string(total.fail),
      )
      print_fails(total)
      // The hard gate: zero genuine spec mismatches, and SIMD genuinely lit up (non-vacuous).
      assert total.fail == 0
      assert total.pass > 0
    }
  }
}

/// The `simd_*.json` fixtures present in `fixtures/`, sorted. Empty when none are vendored.
fn simd_files() -> List(String) {
  case ffi.list_dir(fixtures_dir) {
    Ok(entries) ->
      entries
      |> list.filter(string.starts_with(_, "simd_"))
      |> list.filter(string.ends_with(_, ".json"))
      |> list.sort(string.compare)
    Error(_) -> []
  }
}

fn run_one(d, name: String) -> Report {
  case fixture.load(fixtures_dir <> "/" <> name) {
    Error(e) -> {
      io.println("  " <> name <> " parse error: " <> e)
      runner.empty_report()
    }
    Ok(fix) -> runner.run_fixture(d, fix, fixtures_dir)
  }
}

// ─────────────────────────── the per-family breakdown ───────────────────────────

/// A per-family (int / float / memory+lane / other) pass/skip/fail roll-up, so a single mis-lowered
/// lane family is legible as a NAMED group rather than a diffuse total.
type Families {
  Families(int: Report, float: Report, mem: Report, other: Report)
}

fn new_families() -> Families {
  Families(
    int: runner.empty_report(),
    float: runner.empty_report(),
    mem: runner.empty_report(),
    other: runner.empty_report(),
  )
}

/// Which family a `simd_*.json` fixture belongs to, from its filename — `f32`/`f64` → float; a
/// memory/lane-access file → mem; an integer-lane file → int; everything else (const/conversions/
/// bitwise/boolean/select/linking) → other.
fn family_of(name: String) -> String {
  let is_float = string.contains(name, "f32") || string.contains(name, "f64")
  let is_mem =
    string.contains(name, "load")
    || string.contains(name, "store")
    || string.contains(name, "lane")
    || string.contains(name, "address")
    || string.contains(name, "memory")
  let is_int =
    string.contains(name, "i8x16")
    || string.contains(name, "i16x8")
    || string.contains(name, "i32x4")
    || string.contains(name, "i64x2")
  case is_float, is_mem, is_int {
    True, _, _ -> "float"
    False, True, _ -> "mem"
    False, False, True -> "int"
    False, False, False -> "other"
  }
}

fn add_family(f: Families, fam: String, rep: Report) -> Families {
  case fam {
    "int" -> Families(..f, int: runner.merge(f.int, rep))
    "float" -> Families(..f, float: runner.merge(f.float, rep))
    "mem" -> Families(..f, mem: runner.merge(f.mem, rep))
    _ -> Families(..f, other: runner.merge(f.other, rep))
  }
}

fn print_families(f: Families) -> Nil {
  print_family("int   ", f.int)
  print_family("float ", f.float)
  print_family("mem   ", f.mem)
  print_family("other ", f.other)
}

fn print_family(label: String, r: Report) -> Nil {
  io.println(
    "  ["
    <> label
    <> "] pass="
    <> int.to_string(r.pass)
    <> "  skip="
    <> int.to_string(r.skip)
    <> "  fail="
    <> int.to_string(r.fail),
  )
}

fn print_fails(r: Report) -> Nil {
  case r.fails {
    [] -> Nil
    fails -> {
      io.println("  SIMD FAILURES (first 40):")
      fails
      |> list.take(40)
      |> list.each(fn(x) { io.println("    * " <> x) })
    }
  }
}
